### PR TITLE
Upgrading `fuels` to `0.96.0`

### PR DESCRIPTION
**Pull request by arboleya**
# Summary

Upgrading `fuels` to `0.96.0`.

```
LICENSE:
The Fuel Support team submits this PR to help you use the fuel SDKs. It is provided "as is" 
and without warranty for any purpose. We are not participants in the project at hand. 
All the rights of this code are reserved to the authors of this repository.
```

### CODE REVIEW

**Review by petertonysmith94 — COMMENTED** [review]
Does `@fuel-ts/merkle` need to be `0.96.0` in `packages/tests/package.json`?

**Comment by arboleya** [comment]
@petertonysmith94 good catch. It can be, but shouldn't break anything if it's not.

**Comment by petertonysmith94** [comment]
> @petertonysmith94 good catch. It can be, but shouldn't break anything if it's not.

Just doing a full audit of all PR's :)

**Comment by arboleya** [comment]
Closing in favor of:
 - https://github.com/Bako-Labs/bako-safe/pull/9

**Pull request closed without merging**
